export const TWCSS = {
  container: "px-2 py-2 sm:px-10 sm:pb-5",
  overview: [
    "relative",
    "bg-[var(--color-bg-light-primary-100)] rounded-[8px]",
    "p-6 flex flex-col gap-2 border-b-4 border-transparent",
    "transition-all duration-300 ease-out",
    "hover:-translate-y-1.5 hover:shadow-xl hover:scale-[1.02]",
    "hover:border-b-[var(--color-primary)]",
    "outline outline-[var(--color-unavailable-300)]",
  ],
  paginationButton: [
    "rounded-[8px] transition bg-[var(--color-bg-light-primary-300)]",
    " hover:bg-[var(--color-primary)] hover:text-[var(--color-bg-light-primary-100)]",
  ],
  list: "w-full h-full px-3 md:px-6",
  tagButton: [
    "px-3 py-1.5 rounded-full text-sm font-medium transition-all duration-200",
    "gap-1 border-1 border-[var(--color-gray-400)]",
    "hover:bg-[var(--color-primary)]/5 hover:text-[var(--color-primary-700)] hover:border-[var(--color-primary-700)]",
  ],
  tagButtonActive: ["bg-[var(--color-primary)] text-white border-[var(--color-primary)]"],
  button: [
    "py-2 px-3 border border-[var(--color-unavailable-300)]",
    "gap-2 bg-[var(--color-bg-light-primary-100)] text-sm",
    "hover:bg-[var(--color-primary-100)]",
    "transition-all",
  ],
  input: [
    "flex items-center mt-1 transition-all",
    "border border-[var(--color-unavailable-300)]",
    "focus-within:shadow-[var(--shadow-focus)]",
    "focus-within:border-[var(--color-primary-300)]",
    "focus-within:bg-white",
    "bg-[var(--color-unavailable-100)]/40",
  ],
  tagInput: [
    "w-full rounded-lg border-2 border-transparent p-3 ",
    "focus-within:border-[var(--color-primary)] bg-[var(--color-unavailable-100)]",
  ],
  select: [
    "shadow-[var(--shadow-focus)]",
    "border-[var(--color-primary-300)]",
    "bg-white",
    "bg-[var(--color-unavailable-100)]",
  ],
  inputError: ["outline outline-[var(--color-error-300)]"],
  textarea: [
    "flex items-center p-3 rounded-[8px] mt-1",
    "border-2 border-transparent",
    "focus-within:border-2 focus-within:border-[var(--color-primary)]",
    "bg-[var(--color-unavailable-100)]/40",
  ],
  scrollbarX: [
    "[&::-webkit-scrollbar]:h-2 [&::-webkit-scrollbar-track]:rounded-full",
    "[&::-webkit-scrollbar-track]:bg-gray-100 [&::-webkit-scrollbar-thumb]:rounded-full",
    "[&::-webkit-scrollbar-thumb]:bg-gray-300",
    "dark:[&::-webkit-scrollbar-track]:bg-[var(--color-primary-100)] dark:[&::-webkit-scrollbar-thumb]:bg-[var(--color-primary-300)]",
  ],
  scrollbarY: [
    "[&::-webkit-scrollbar]:w-1 [&::-webkit-scrollbar-track]:rounded-full",
    "[&::-webkit-scrollbar-track]:bg-gray-100 [&::-webkit-scrollbar-thumb]:rounded-full",
    "[&::-webkit-scrollbar-thumb]:bg-gray-300",
    "dark:[&::-webkit-scrollbar-track]:bg-[var(--color-primary-100)] dark:[&::-webkit-scrollbar-thumb]:bg-[var(--color-primary-300)]",
  ],
  department: [
    "bg-[var(--color-primary-100)] text-[var(--color-primary)] p-4 rounded-[8px]",
    "hover:bg-[var(--color-primary)] hover:text-white",
    "transition-all duration-300 font-medium",
    "mb-2 flex items-center justify-between",
  ],
};
